/* 사원번호  */
DROP SEQUENCE EMPL_SEQ;
CREATE SEQUENCE EMPL_SEQ START WITH 1 INCREMENT BY 1;

/* 상품번호 */
DROP SEQUENCE SALENUMBER_SEQ;
CREATE SEQUENCE SALENUMBER_SEQ START WITH 1 INCREMENT BY 1;

/* 재고번호 */
DROP SEQUENCE STOCK_LIST_SQ;

/* 회원번호 */
DROP SEQUENCE MEMBERNUMBER_SEQ;
CREATE SEQUENCE MEMBERNUMBER_SEQ START WITH 1000000000000000 INCREMENT BY 1;

/* 일정번호 */
DROP SEQUENCE EVENT_ID_SEQU;
CREATE SEQUENCE EVENT_ID_SEQU START WITH 1 INCREMENT BY 1;

/* 메세지 번호 */
DROP SEQUENCE MESSAGENUMBER_SEQ;
CREATE SEQUENCE MESSAGENUMBER_SEQ START WITH 1 INCREMENT BY 1;

/* 공지게시판 글번호 */
DROP SEQUENCE NOTI_BOARD_SEQ;
CREATE SEQUENCE NOTI_BOARD_SEQ START WITH 1 INCREMENT BY 1;

/* Q&A게시판 글번호 */
DROP SEQUENCE QNA_NUM_SEQU;
CREATE SEQUENCE QNA_NUM_SEQU START WITH 1 INCREMENT BY 1;

/* 아이디어게시판 글번호 */
DROP SEQUENCE IDEA_BOARD_SEQ;
CREATE SEQUENCE IDEA_BOARD_SEQ START WITH 1 INCREMENT BY 1;